name: ebv-scvi
channels:
  - conda-forge
dependencies:
  - jsonschema-specifications=2025.4.1
  - jinja2=3.1.6
  - cffi=1.17.1
  - libllvm20=20.1.8
  - alsa-lib=1.2.14
  - libglvnd=1.7.0
  - terminado=0.18.1
  - tbb=2021.13.0
  - libllvm21=21.1.0
  - comm=0.2.3
  - threadpoolctl=3.6.0
  - libegl=1.7.0
  - keyutils=1.6.3
  - libedit=3.1.20250104
  - importlib_resources=6.5.2
  - sniffio=1.3.1
  - argon2-cffi-bindings=25.1.0
  - pyro-ppl=1.9.1
  - svt-av1=3.1.2
  - tzdata=2025b
  - yaml=0.2.5
  - natsort=8.4.0
  - xorg-libxfixes=6.0.1
  - xorg-libxdmcp=1.1.5
  - xcb-util=0.4.1
  - toolz=1.0.0
  - jupyter_core=5.8.1
  - xorg-libxxf86vm=1.1.6
  - isoduration=20.11.0
  - h5py=3.14.0
  - mpc=1.3.1
  - leidenalg=0.10.2
  - typing_utils=0.1.0
  - libpng=1.6.50
  - jsonpointer=3.0.0
  - httpx=0.28.1
  - debugpy=1.8.16
  - json5=0.12.1
  - python-igraph=0.11.9
  - numba=0.61.2
  - mpfr=4.2.1
  - libfreetype6=2.13.3
  - bzip2=1.0.8
  - ml_dtypes=0.5.1
  - pygments=2.19.2
  - libgcc=15.1.0
  - pynndescent=0.5.13
  - libsqlite=3.50.4
  - libjpeg-turbo=3.1.0
  - charset-normalizer=3.4.3
  - gmpy2=2.2.1
  - lcms2=2.17
  - tomli=2.2.1
  - python-fastjsonschema=2.21.2
  - tinycss2=1.4.0
  - optax=0.2.5
  - executing=2.2.1
  - ld_impl_linux-64=2.44
  - xorg-libxrender=0.9.12
  - chex=0.1.90
  - parso=0.8.5
  - traitlets=5.14.3
  - libgl=1.7.0
  - pyro-api=0.1.2
  - libstdcxx-ng=15.1.0
  - jupyterlab_pygments=0.3.0
  - libglib=2.84.3
  - tornado=6.5.2
  - ncurses=6.5
  - igraph=0.10.16
  - jupyter_server_terminals=0.5.3
  - libnghttp2=1.67.0
  - libxslt=1.1.43
  - libavif16=1.3.0
  - font-ttf-inconsolata=3.000
  - brotli-bin=1.1.0
  - texttable=1.7.0
  - psutil=7.0.0
  - joblib=1.5.2
  - _openmp_mutex=4.5
  - array-api-compat=1.12.0
  - hyperframe=6.1.0
  - libexpat=2.7.1
  - tqdm=4.67.1
  - nest-asyncio=1.6.0
  - webcolors=24.11.1
  - libzlib=1.3.1
  - louvain=0.8.2
  - libnsl=2.0.1
  - libntlm=1.8
  - pcre2=10.45
  - dbus=1.16.2
  - certifi=2025.8.3
  - xorg-libx11=1.8.12
  - hdf5=1.14.6
  - harfbuzz=11.4.5
  - xcb-util-keysyms=0.4.1
  - sleef=3.9.0
  - libtiff=4.7.0
  - libbrotlienc=1.1.0
  - markdown-it-py=4.0.0
  - zipp=3.23.0
  - fonttools=4.59.2
  - lightning=2.5.4
  - referencing=0.36.2
  - xorg-libxcursor=1.2.3
  - et_xmlfile=2.0.0
  - pthread-stubs=0.4
  - matplotlib=3.10.6
  - jupyter-lsp=2.3.0
  - python-dateutil=2.9.0.post0
  - grpcio=1.71.0
  - openldap=2.6.10
  - font-ttf-source-code-pro=2.038
  - uri-template=1.3.0
  - tensorboard=2.20.0
  - mistune=3.1.4
  - prometheus_client=0.22.1
  - fonts-conda-forge=1
  - msgpack-python=1.1.1
  - xorg-libxi=1.8.2
  - pickleshare=0.7.5
  - h2=4.3.0
  - jupyter_events=0.12.0
  - numpy=2.2.6
  - libiconv=1.18
  - scikit-learn=1.7.1
  - pexpect=4.9.0
  - matplotlib-base=3.10.6
  - xorg-libsm=1.2.6
  - idna=3.10
  - setuptools=80.9.0
  - qhull=2020.2
  - decorator=5.2.1
  - scikit-misc=0.5.1
  - statsmodels=0.14.5
  - sparse=0.17.0
  - jupyterlab=4.4.7
  - torchmetrics=1.8.2
  - platformdirs=4.4.0
  - pybind11-global=2.13.6
  - gmp=6.3.0
  - absl-py=2.3.1
  - python_abi=3.10
  - icu=75.1
  - rpds-py=0.27.1
  - libfreetype=2.13.3
  - pip=25.2
  - tensorstore=0.1.65
  - ptyprocess=0.7.0
  - libstdcxx=15.1.0
  - xorg-libxdamage=1.1.6
  - argon2-cffi=25.1.0
  - blosc=1.21.6
  - cpython=3.10.18
  - mudata=0.3.1
  - tensorboard-data-server=0.7.0
  - python=3.10.18
  - libblas=3.9.0
  - flax=0.10.2
  - six=1.17.0
  - notebook-shim=0.2.4
  - urllib3=2.5.0
  - defusedxml=0.7.1
  - openssl=3.5.2
  - soupsieve=2.8.1
  - mdurl=0.1.2
  - jaxlib=0.6.2
  - libxcb=1.17.0
  - lerc=4.0.0
  - nbclient=0.10.2
  - typing-extensions=4.15.0
  - orbax-checkpoint=0.8.0
  - libclang13=21.1.0
  - ca-certificates=2025.8.3
  - pysocks=1.7.1
  - brotli=1.1.0
  - xcb-util-renderutil=0.3.10
  - libssh2=1.11.1
  - fonts-conda-ecosystem=1
  - jedi=0.19.2
  - pyzmq=27.0.2
  - libxcrypt=4.4.36
  - attrs=25.3.0
  - libre2-11=2025.06.26
  - overrides=7.7.0
  - libev=4.33
  - prompt-toolkit=3.0.52
  - python-json-logger=2.0.7
  - beautifulsoup4=4.13.5
  - ipykernel=6.30.1
  - libpq=17.6
  - python-tzdata=2025.2
  - libcblas=3.9.0
  - xcb-util-cursor=0.1.5
  - openpyxl=3.1.5
  - unicodedata2=16.0.0
  - pyyaml=6.0.2
  - pandas=2.3.2
  - humanize=4.13.0
  - libbrotlidec=1.1.0
  - seaborn-base=0.13.2
  - arpack=3.9.1
  - markupsafe=3.0.2
  - importlib-metadata=8.7.0
  - fsspec=2025.9.0
  - libxkbcommon=1.11.0
  - docrep=0.3.2
  - packaging=25.0
  - dav1d=1.2.1
  - umap-learn=0.5.9.post2
  - jax=0.6.2
  - libgcc-ng=15.1.0
  - async-lru=2.0.5
  - rav1e=0.7.1
  - libffi=3.4.6
  - libgfortran=15.1.0
  - libdeflate=1.24
  - libxml2=2.13.8
  - libprotobuf=5.29.3
  - libuuid=2.38.1
  - jupyter_server=2.17.0
  - babel=2.17.0
  - zeromq=4.3.5
  - filelock=3.19.1
  - libtorch=2.7.1
  - xorg-libxrandr=1.5.4
  - pytz=2025.2
  - brotli-python=1.1.0
  - libuv=1.51.0
  - pyparsing=3.2.3
  - openjpeg=2.5.3
  - pycparser=2.22
  - numpyro=0.19.0
  - anyio=4.10.0
  - aom=3.9.1
  - scvi-tools=1.3.3
  - xcb-util-image=0.4.0
  - httpcore=1.0.9
  - libleidenalg=0.11.1
  - double-conversion=3.3.1
  - libdrm=2.4.125
  - libaec=1.1.4
  - font-ttf-dejavu-sans-mono=2.37
  - rich=14.1.0
  - rfc3987-syntax=1.1.0
  - ml-collections=1.0.0
  - pybind11-abi=4
  - ipython=8.37.0
  - asttokens=3.0.0
  - matplotlib-inline=0.1.7
  - libwebp-base=1.6.0
  - zstd=1.5.7
  - etils=1.12.2
  - pytorch-lightning=2.5.4
  - lark=1.2.2
  - opt_einsum=3.4.0
  - lightning-utilities=0.15.2
  - font-ttf-ubuntu=0.83
  - munkres=1.1.4
  - libglx=1.7.0
  - wcwidth=0.2.13
  - scanpy=1.11.4
  - legacy-api-wrap=1.4.1
  - libabseil=20250127.1
  - libsodium=1.0.20
  - fqdn=1.5.1
  - llvmlite=0.44.0
  - re2=2025.06.26
  - jsonschema-with-format-nongpl=4.25.1
  - multipledispatch=0.6.0
  - patsy=1.0.1
  - rfc3986-validator=0.1.1
  - liblzma=5.8.1
  - types-python-dateutil=2.9.0.20250822
  - protobuf=5.29.3
  - cached_property=1.5.2
  - libpciaccess=0.18
  - libcups=2.3.3
  - cairo=1.18.4
  - zstandard=0.24.0
  - libhwloc=2.12.1
  - rfc3339-validator=0.1.4
  - websocket-client=1.8.0
  - send2trash=1.8.3
  - contourpy=1.3.2
  - glpk=5.0
  - xcb-util-wm=0.4.2
  - xorg-libxtst=1.2.5
  - mpmath=1.3.0
  - libclang-cpp20.1=20.1.8
  - bleach=6.2.0
  - scipy=1.15.2
  - lz4-c=1.10.0
  - seaborn=0.13.2
  - bleach-with-css=6.2.0
  - sympy=1.14.0
  - networkx=3.4.2
  - nbconvert-core=7.16.6
  - snappy=1.2.2
  - werkzeug=3.1.3
  - krb5=1.21.3
  - nbformat=5.10.4
  - cycler=0.12.1
  - hpack=4.1.0
  - jupyter_client=8.6.3
  - session-info2=0.2.1
  - pandocfilters=1.5.0
  - fontconfig=2.15.0
  - wheel=0.45.1
  - libgrpc=1.71.0
  - readline=8.2
  - wayland=1.24.0
  - mkl=2024.2.2
  - pixman=0.46.4
  - pyside6=6.9.2
  - llvm-openmp=21.1.0
  - xorg-libxext=1.3.6
  - colorama=0.4.6
  - liblapack=3.9.0
  - pybind11=2.13.6
  - arrow=1.3.0
  - requests=2.32.5
  - xarray=2025.6.1
  - stack_data=0.6.3
  - tk=8.6.13
  - webencodings=0.5.1
  - jsonschema=4.25.1
  - kiwisolver=1.4.9
  - freetype=2.13.3
  - pytorch=2.7.1
  - typing_extensions=4.15.0
  - xkeyboard-config=2.45
  - xorg-libxcomposite=0.4.6
  - graphite2=1.3.14
  - libgfortran5=15.1.0
  - cached-property=1.5.2
  - libbrotlicommon=1.1.0
  - xorg-libice=1.1.2
  - libcurl=8.14.1
  - cyrus-sasl=2.1.28
  - markdown=3.8.2
  - pure_eval=0.2.3
  - qt6-main=6.9.2
  - exceptiongroup=1.3.0
  - jupyterlab_server=2.27.3
  - optree=0.17.0
  - h11=0.16.0
  - pillow=11.3.0
  - anndata=0.11.4
  - libopengl=1.7.0
  - xorg-libxau=1.0.12
  - c-ares=1.34.5
  - pyarrow
prefix: /home/glen/miniforge3/envs/ebv-scvi
  - pip
  - pip:
      - gseapy
      - mygene
